# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johan Nainggolan
email: johandata@yahoo.com
description:  Learning and Documenting !
             
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jolabti.github.io" # the base hostname & protocol for your site
twitter_username: devgolan
github_username:  jolabti

# Build settings
markdown: kramdown
